# Generated by Django 4.2.5 on 2023-09-08 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='user_id',
            new_name='user',
        ),
    ]
